### ISSUE TITLE
No targets matched selector

### ISSUE THREAD

**Issue by GoodLucky777** [wode490390/VanillaCommands#2]
I can't use target things, it almost always says ```No targets matched selector```.

**Comment by wode490390** [comment]
Which command did you use?

**Comment by GoodLucky777** [comment]
every commands that use target

**Comment by wode490390** [comment]
![](https://user-images.githubusercontent.com/17339354/78370944-e9eab100-75f9-11ea-97a0-37227fce8597.png)
![](https://user-images.githubusercontent.com/17339354/78370953-ec4d0b00-75f9-11ea-9a17-2728050646f7.png)

It works fine.

**Comment by GoodLucky777** [comment]
Is this plugin conflict with other plugin?

**Comment by GoodLucky777** [comment]
```
> testfor @a
17:11:15 [INFO ] No targets matched selector
```
Even though there are players on the server, it says there are no players.

**Comment by wode490390** [comment]
![](https://user-images.githubusercontent.com/17339354/78464935-3b8e5b00-7722-11ea-8598-a04ff649a231.png)

Hmmm, I know why you can't match any targets.

https://github.com/wode490390/VanillaCommands/blob/69521ae012fba8d2c91897bd5531f4a3697263a2/src/main/java/cn/wode490390/nukkit/vcmd/EntitySelector.java#L139-L154

**Comment by GoodLucky777** [comment]
So, it select only default world when I use in the console. Am I right?

**Comment by GoodLucky777** [comment]
Can you make a target selector like ```@e[world=world2]```?

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/VanillaCommands/commit/0abcd75e328c0919b55c88dfd3cca6b6b3d8ab98.

**Comment by Kali358** [comment]
Guys, can pls some body help me 🙏? Every time I tried to get item with cheat it says no targets matched selector. Pls heeeeelp 🙏🙏🙏
